### ISSUE TITLE
x found nothing to do in the 'ba' column

### ISSUE THREAD

**Issue by jamiely** [secretGeek/devShop#3]
It seems like there may be some bug around a BA self-starting. I get the message that the BA found nothing to do in the BA column. Was there previously a BA column? Was it renamed Inbox?

**Comment by secretGeek** [comment]
The bug is: column name not ID should be used in that message. 

Self starter also needs to be a little clearer how it works. In another issue is adding the self start level on each worker.

**Comment by secretGeek** [comment]
fixed the bug itself.
