### ISSUE TITLE
Self-starter not applying

### ISSUE THREAD

**Issue by ben-walcutt** [secretGeek/devShop#4]
When I purchased self starter, it doesn't seem to work. None of my people grab tasks automatically. Nor does the UI even show who the self-starter applies to.

**Comment by AddisonBostian** [comment]
think it does work, just not as it first seems. It looks like self starter is a leveled skill, where the number of items a worker will self start before you're required to take action again, is equal to the self start skill level. So if you purchase self start twice for one worker, after you start one task with them, they will auto start 2 more, then sit idle and wait for intervention.

edit: There is also a 3 second delay before they will pick an item up.

**Comment by khromov** [comment]
>  if you purchase self start twice for one worker, after you start one task with them, they will auto start 2 more, then sit idle and wait for intervention.

I thought this game was a "cookie clicker", but the whole point of this genre is that games play themselves after a while and you optimize processes. If you constantly have to take manual actions, this game is not what I expected.

**Comment by loispostula** [comment]
Perhaps self starter should be 
Will search for work after xx seconds and the time increase after each self start.
By buying self starter, you reduce this multiplicator?

**Comment by secretGeek** [comment]
Yeh @LoisPostula I think you’re right, something like that would resolve a lot of people’s confusion. 

Originally I resisted doing it that way as I didn’t want it to turn into a straight “cookie clicker” game. But I think what I’ve seen from peoples responses here and on HN is that the self starter behavior is very confusing. Even if I added a little self starter icon with a number people would continue to be confused that the self starter doesn’t self-start. 

So I think I’ll try it with a gap between self starts, and the gap decreases if they have a higher level of initiative. (Ah yeh - I plan to call it initiative too, D&D style).

**Comment by SarahGG** [comment]
@secretGeek I think that would be a great idea. I thought the current functionality was a bug!

**Comment by secretGeek** [comment]
self-starter and observant skills have been replaced with "initiative" which means a worker keeps going back and getting more cards to do. If they only have level 1 initiative they wait a while before grabbing a card. Give them more initiative and they will go back sooner each time.
