### ISSUE TITLE
What do 🥑and 🥓represent?

### ISSUE THREAD

**Issue by awiso** [secretGeek/devShop#8]

**Comment by James-Quigley** [comment]
If you hover, they represent the level, and XP necessary to level up. So far as far as I can tell levels just unlock new items in the store

**Comment by awiso** [comment]
Ah ok
I hadn't hovered long enough to get that info
Thanks

**Comment by secretGeek** [comment]
Cheers. Yeh they’re not exactly intuitive. There’s no universally agreed in emoji for level and XP, so I just went with something kind of whimsical.
