### ISSUE TITLE
Self-starter level check

### ISSUE THREAD

**Issue by jessmartin** [secretGeek/devShop#9]
When applying the Self-Starter power-up, it would be nice to see how many self-starters each of my workers have. That way I can give the power-up to someone who actually can use it.

**Comment by secretGeek** [comment]
Can definitely do this. I’ll show the rocket icon on the person with a little number, the same way as is shown on other skills.

**Comment by secretGeek** [comment]
This is done now @jessmartin  👍

**Comment by jessmartin** [comment]
> This is done now @jessmartin 👍

Nice! I was thinking about how to implement it last night... 😄 

Also, see #10
